repo_url: https://netxxus.github.io/mytiendanx/repo
repo_name: Netxxus Store TV
repo_description: Mi tienda privada de aplicaciones para Android TV
repo_keyalias: DESKTOP-5U1F3KN.localdomain
keystorepass: mq9jQLXszHw4XN5TqzVGQPN/NrzTA/3NxCCGu4sAZI0=
keypass: mq9jQLXszHw4XN5TqzVGQPN/NrzTA/3NxCCGu4sAZI0=
